// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// crcwish
arma::cube crcwish(int n, arma::mat Sigma, double nu, arma::mat a, arma::mat b, int npairs);
RcppExport SEXP _cdists_crcwish(SEXP nSEXP, SEXP SigmaSEXP, SEXP nuSEXP, SEXP aSEXP, SEXP bSEXP, SEXP npairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type npairs(npairsSEXP);
    rcpp_result_gen = Rcpp::wrap(crcwish(n, Sigma, nu, a, b, npairs));
    return rcpp_result_gen;
END_RCPP
}
// cpropose_gwish
arma::cube cpropose_gwish(int n, arma::mat Sigma, double nu, arma::mat a, int npairs);
RcppExport SEXP _cdists_cpropose_gwish(SEXP nSEXP, SEXP SigmaSEXP, SEXP nuSEXP, SEXP aSEXP, SEXP npairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type npairs(npairsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpropose_gwish(n, Sigma, nu, a, npairs));
    return rcpp_result_gen;
END_RCPP
}
// cr_ordinary_wish
arma::cube cr_ordinary_wish(int n, arma::mat Sigma, double nu, int npairs);
RcppExport SEXP _cdists_cr_ordinary_wish(SEXP nSEXP, SEXP SigmaSEXP, SEXP nuSEXP, SEXP npairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type npairs(npairsSEXP);
    rcpp_result_gen = Rcpp::wrap(cr_ordinary_wish(n, Sigma, nu, npairs));
    return rcpp_result_gen;
END_RCPP
}
// cr_ordinary_mvn
arma::mat cr_ordinary_mvn(int n, arma::mat Sigma, arma::colvec mu);
RcppExport SEXP _cdists_cr_ordinary_mvn(SEXP nSEXP, SEXP SigmaSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(cr_ordinary_mvn(n, Sigma, mu));
    return rcpp_result_gen;
END_RCPP
}
// crtmvn
arma::mat crtmvn(int n, arma::mat Sigma, arma::colvec mu, arma::colvec a, arma::colvec b);
RcppExport SEXP _cdists_crtmvn(SEXP nSEXP, SEXP SigmaSEXP, SEXP muSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(crtmvn(n, Sigma, mu, a, b));
    return rcpp_result_gen;
END_RCPP
}
// crtmvt
arma::mat crtmvt(int n, arma::mat Sigma, arma::colvec mu, double nu, arma::colvec a, arma::colvec b);
RcppExport SEXP _cdists_crtmvt(SEXP nSEXP, SEXP SigmaSEXP, SEXP muSEXP, SEXP nuSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(crtmvt(n, Sigma, mu, nu, a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cdists_crcwish", (DL_FUNC) &_cdists_crcwish, 6},
    {"_cdists_cpropose_gwish", (DL_FUNC) &_cdists_cpropose_gwish, 5},
    {"_cdists_cr_ordinary_wish", (DL_FUNC) &_cdists_cr_ordinary_wish, 4},
    {"_cdists_cr_ordinary_mvn", (DL_FUNC) &_cdists_cr_ordinary_mvn, 3},
    {"_cdists_crtmvn", (DL_FUNC) &_cdists_crtmvn, 5},
    {"_cdists_crtmvt", (DL_FUNC) &_cdists_crtmvt, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_cdists(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
