# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crcwish <- function(n, Sigma, nu, a, b, npairs) {
    .Call(`_cdists_crcwish`, n, Sigma, nu, a, b, npairs)
}

cpropose_gwish <- function(n, Sigma, nu, a, npairs) {
    .Call(`_cdists_cpropose_gwish`, n, Sigma, nu, a, npairs)
}

crtmvn <- function(n, Sigma, mu, a, b) {
    .Call(`_cdists_crtmvn`, n, Sigma, mu, a, b)
}

crtmvt <- function(n, Sigma, mu, nu, a, b) {
    .Call(`_cdists_crtmvt`, n, Sigma, mu, nu, a, b)
}

