# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crcwish <- function(n, Sigma, nu, a, b, npairs) {
    .Call(`_cdists_crcwish`, n, Sigma, nu, a, b, npairs)
}

crgwish <- function(n, Sigma, nu, a, npairs) {
    .Call(`_cdists_crgwish`, n, Sigma, nu, a, npairs)
}

cr_ordinary_wish <- function(n, Sigma, nu, npairs) {
    .Call(`_cdists_cr_ordinary_wish`, n, Sigma, nu, npairs)
}

cr_ordinary_mvn <- function(n, Sigma, mu) {
    .Call(`_cdists_cr_ordinary_mvn`, n, Sigma, mu)
}

crtmvn <- function(n, Sigma, mu, a, b) {
    .Call(`_cdists_crtmvn`, n, Sigma, mu, a, b)
}

crtmvt <- function(n, Sigma, mu, nu, a, b, scale_term) {
    .Call(`_cdists_crtmvt`, n, Sigma, mu, nu, a, b, scale_term)
}

